cache:
    paths:
        - vendor/

before_script:
    - bash ci/docker-install.sh > /dev/null
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - php composer.phar install --prefer-source --no-interaction

test:5.6:
    image: php:5.6
    script:
        - php composer.phar test-all

test:7.0:
    image: php:7.0
    script:
        - php composer.phar test-all

test:7.1:
    image: php:7.1
    script:
        - php composer.phar test-all
