language: php
php:
    - 7.1
#    - '5.6'
#    - '7.0'
#    - '7.1'
#    - hhvm
#    @TODO: Make compatible with previous PHP versions!
before_script:
    - composer self-update
    - composer install --no-interaction
script:
    - composer test-all
